version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=ctr
    ports:
      - '5433:5432'
  ctr:
    image: adexcel_ctr
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
